# Generated by Django 5.1.6 on 2025-03-04 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField()),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online Transfer')], max_length=50)),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_screenshot', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
