# Generated by Django 5.1.6 on 2025-03-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GownPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cap', 'Cap'), ('Hood', 'Hood'), ('Tassel', 'Tassel'), ('Gown', 'Gown')], max_length=50)),
            ],
        ),
    ]
